#!/bin/bash
#===============================================================================
# Author         : Swapan Mallick, SMHI
# Date Created   : 19/12/2025
#===============================================================================

#-------------------------------
#SBATCH --job-name=ML-plots
#SBATCH --output=ML_PLOTS.log
#SBATCH --error=ML_PLOTS.log
#SBATCH --qos=nf
#SBATCH --nodes=1
#SBATCH --time=48:00:00
#-------------------------------

# Load modules and activate environment
set -evx
module load conda
conda activate climate

# ---------------------------
# Define paths
# ---------------------------
VAR="t2m"

# Generate 6-hourly DATE_ARRAY automatically
DATE_ARRAY=()
for t in $(seq 0 6 124); do  # 124 for 31 days
  DATE_ARRAY+=($(date -u -d "2020-01-01 +${t} hour" +"%Y%m%d%H"))
done

SCR=${PWD}
CERRADATA="/lus/h2resw01/scratch/swe4281/CERRA_DATA2026/PROCESS/netcdf_cerra"
ERRA5EDA="/lus/h2resw01/scratch/swe4281/CERRA_DATA2026/PROCESS/netcdf_era5eda"
OUTPUT="/lus/h2resw01/scratch/swe4281/CERRA_DATA2026/PROCESS"
#
mkdir -p "${OUTPUT}/ML_PLOTS"
mkdir -p "${OUTPUT}/ML_plots"


# ---------------------------
# Loop through each date
# ---------------------------
for YYMMDDHH in "${DATE_ARRAY[@]}"; do
    echo "=================================================="
    echo "Processing date: $YYMMDDHH "
    echo "=================================================="

    YYYY=${YYMMDDHH:0:4}
    MM=${YYMMDDHH:4:2}
    DD=${YYMMDDHH:6:2}
    HH=${YYMMDDHH:8:2}
    YYMM=${YYYY}${MM}
    echo ${YYYY}${MM}

    TMP="${SCR}/tmp_${VAR}_${YYMMDDHH}"
    rm -rf ${TMP}
    mkdir -p ${TMP}
    cd ${TMP}

    echo "Copying data files for date: $YYMMDDHH"
    ln -sf ${CERRADATA}/cerra_t2m_points_${YYMMDDHH}.nc ./ 
    ln -sf ${ERRA5EDA}/era5eda_${VAR}_points_${YYMMDDHH}.nc ./ 

    #exit 0

    echo "Verifying copied files:"
    ls -la ${TMP}/
    python3 ${SCR}/plot_era5cerra_ML_IMAGE.py --cerra_file cerra_t2m_points_${YYMMDDHH}.nc --era_file era5eda_${VAR}_points_${YYMMDDHH}.nc 
    # move all the output in a safe place
    mv ${TMP}/*.png        ${OUTPUT}/ML_plots
    python3 ${SCR}/plot_era5cerra_ML_IMAGE_SCALE.py --cerra_file cerra_t2m_points_${YYMMDDHH}.nc --era_file era5eda_${VAR}_points_${YYMMDDHH}.nc 
    # move all the output in a safe place
    mv ${TMP}/*.png        ${OUTPUT}/ML_PLOTS
    #
    #exit 0
    rm -rf ${TMP}
    cd ${SCR}
    echo "=================================================="
    echo "Completed processing date: $YYMM$HH"
    echo "=================================================="
    echo ""

done

echo "All dates processed successfully!"
exit 0
