# -*- coding: utf-8 -*-
"""
Author      : Swapan Mallick (SMHI)
Created on  : 2025-12-15

Description
-----------
This script compares point-based CERRA reanalysis and ERA5-EDA datasets

The input NetCDF files are generated by the preprocessing pipeline of the
Diffusion_CERRA project and contain:
    - Ensemble mean (t2m_mean)
    - Ensemble standard deviation (t2m_std)
at selected spatial points within a predefined European domain.

Main functionalities:
    1. Read point-based NetCDF outputs for CERRA and ERA5-EDA
    2. Extract ensemble mean and standard deviation fields
    3. Generate plots for:
        - Mean temperature comparison
        - Standard deviation comparison
    4. Save PNG figures for each timestamp

Plots are produced in geographic (latitude/longitude) coordinates and are
intended for:
    - Model intercomparison
    - Uncertainty assessment

Input
-----
- cerra_t2m_points_YYYYMMDDHH.nc
- era5eda_t2m_points_YYYYMMDDHH.nc

Output
------
- CerraEra_Mean_YYYYMMDDHH.png
- CerraEra_SD_YYYYMMDDHH.png

Dependencies
------------
xarray, numpy, matplotlib, cartopy

Part of
-------
Diffusion_CERRA: CERRA and ERA5-EDA Ensemble Analysis and Diffusion Modeling Framework
"""
import xarray as xr
import matplotlib.pyplot as plt
import numpy as np
import os
import time


filename1 = "cerra_t2m_points_2020010100.nc"
filename2 = "era5eda_t2m_points_2020010100.nc"

start_time = time.time()
def extract_timestamp(filename):
    basename = os.path.basename(filename)
    name_without_ext = os.path.splitext(basename)[0]
    return name_without_ext[-10:]

timestamp = extract_timestamp(filename2)
print(f"Timestamp extracted: {timestamp}")

DOMAIN = {
    'lon_min': -11.0,
    #'lon_min': -20.0,
    #'lon_max': 40.0,
    'lon_max': 30.0,
    'lat_min': 35.0,
    'lat_max': 72.0
}

print(f"Using fixed domain: Lon {DOMAIN['lon_min']} to {DOMAIN['lon_max']}, "
      f"Lat {DOMAIN['lat_min']} to {DOMAIN['lat_max']}")

# Load data 
ds_ce = xr.open_dataset(filename1, chunks={'points': 1000})
ds_er = xr.open_dataset(filename2, chunks={'points': 1000})

# Extract data 
print("Extracting data...")
data_mean_ce = ds_ce['t2m_mean'].load()
data_sd_ce = ds_ce['t2m_std'].load()
data_mean_er = ds_er['t2m_mean'].load()
data_sd_er = ds_er['t2m_std'].load()

def get_valid_data_within_domain(data_array, domain):
    values = data_array.values
    lats = data_array.latitude.values
    lons = data_array.longitude.values

    # Create masks
    valid_mask = ~np.isnan(values)
    domain_mask = (
        (lats >= domain['lat_min']) & (lats <= domain['lat_max']) &
        (lons >= domain['lon_min']) & (lons <= domain['lon_max'])
    )

    # Combined mask: valid AND within domain
    combined_mask = valid_mask & domain_mask

    if np.any(combined_mask):
        return (
            lons[combined_mask],
            lats[combined_mask],
            values[combined_mask],
            combined_mask
        )
    return (None, None, None, combined_mask)

print("Processing CERRA data within domain...")
# 
cerra_mean_data = get_valid_data_within_domain(data_mean_ce, DOMAIN)
cerra_sd_data = get_valid_data_within_domain(data_sd_ce, DOMAIN)

print("Processing ERA5 data within domain...")
# 
era_mean_data = get_valid_data_within_domain(data_mean_er, DOMAIN)
era_sd_data = get_valid_data_within_domain(data_sd_er, DOMAIN)

# 
PLOT_PARAMS = {
    'mean': {'vmin': 200, 'vmax': 300, 'cmap': 'jet', 'label': 'Temperature (K)'},
    'sd': {'vmin': 0, 'vmax': 3, 'cmap': 'jet', 'label': 'Standard Deviation (K)'}
}

def create_scatter_plot_fixed_domain(ax, lons_valid, lats_valid, values_valid, 
                                    plot_type, title, add_colorbar=True):
    """Create a scatter plot with fixed domain boundaries"""
    if lons_valid is not None and len(lons_valid) > 0:
        params = PLOT_PARAMS[plot_type]

        # Create scatter plot
        scatter = ax.scatter(lons_valid, lats_valid, c=values_valid,
                           cmap=params['cmap'], s=5, alpha=0.7,
                           vmin=params['vmin'], vmax=params['vmax'])

        ax.set_xlabel('Longitude')
        ax.set_ylabel('Latitude')
        ax.set_title(title)

        # Set fixed domain boundaries
        ax.set_xlim(DOMAIN['lon_min'], DOMAIN['lon_max'])
        ax.set_ylim(DOMAIN['lat_min'], DOMAIN['lat_max'])

        # Add grid
        ax.grid(True, alpha=0.3, linestyle='--')

        # Add colorbar if requested
        if add_colorbar:
            cbar = plt.colorbar(scatter, ax=ax, orientation='horizontal',
                              pad=0.05, label=params['label'])
            cbar.solids.set(alpha=1)
        
        # Count points 
        points_count = len(lons_valid)

        # Add statistics text box
        if points_count > 0:
            stats_text = f'Points: {points_count}\n'
            stats_text += f'Min: {values_valid.min():.2f}\n'
            stats_text += f'Max: {values_valid.max():.2f}\n'
            stats_text += f'Mean: {values_valid.mean():.2f}'

            #ax.text(0.02, 0.98, stats_text, transform=ax.transAxes,
            #       fontsize=8, verticalalignment='top',
            #       bbox=dict(boxstyle='round', facecolor='white', alpha=0.8))

        return True, points_count
    else:
        #ax.text(0.5, 0.5, 'No valid data\nwithin domain', ha='center', va='center',
        #       transform=ax.transAxes, fontsize=12)
        ax.set_title(f'{title} - No Data')

        # Still set the domain boundaries
        ax.set_xlim(DOMAIN['lon_min'], DOMAIN['lon_max'])
        ax.set_ylim(DOMAIN['lat_min'], DOMAIN['lat_max'])
        ax.grid(True, alpha=0.3, linestyle='--')

        return False, 0

# --- FIGURE 1: 
print("Creating mean temperature comparison plot...")
fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5), constrained_layout=True)
# 
lons_ce_mean, lats_ce_mean, vals_ce_mean, _ = cerra_mean_data
lons_er_mean, lats_er_mean, vals_er_mean, _ = era_mean_data

# 
plot1_success, ce_mean_count = create_scatter_plot_fixed_domain(
    ax1, lons_ce_mean, lats_ce_mean, vals_ce_mean,
    'mean', 'CERRA t2m Mean'
)

plot2_success, er_mean_count = create_scatter_plot_fixed_domain(
    ax2, lons_er_mean, lats_er_mean, vals_er_mean,
    'mean', 'ERA5-EDA t2m Mean'
)

plt.suptitle(f'Mean Temperature Comparison - {timestamp}\n'
            f'Domain: Lon {DOMAIN["lon_min"]}° to {DOMAIN["lon_max"]}°, '
            f'Lat {DOMAIN["lat_min"]}° to {DOMAIN["lat_max"]}°',
            fontsize=14, fontweight='bold')

# Save with optimized settings
mean_output_filename = f"CerraEra_Mean_{timestamp}.png"
plt.savefig(mean_output_filename, dpi=100, bbox_inches='tight')
print(f"Mean comparison saved as: {mean_output_filename}")
plt.close(fig1)

# --- FIGURE 2: 
print("Creating standard deviation comparison plot...")
fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(10, 5), constrained_layout=True)

# 
lons_ce_sd, lats_ce_sd, vals_ce_sd, _ = cerra_sd_data
lons_er_sd, lats_er_sd, vals_er_sd, _ = era_sd_data

# 
plot3_success, ce_sd_count = create_scatter_plot_fixed_domain(
    ax3, lons_ce_sd, lats_ce_sd, vals_ce_sd,
    'sd', 'CERRA t2m Standard Deviation'
)

plot4_success, er_sd_count = create_scatter_plot_fixed_domain(
    ax4, lons_er_sd, lats_er_sd, vals_er_sd,
    'sd', 'ERA5-EDA t2m Standard Deviation'
)

plt.suptitle(f'Standard Deviation Comparison - {timestamp}\n'
            f'Domain: Lon {DOMAIN["lon_min"]}° to {DOMAIN["lon_max"]}°, '
            f'Lat {DOMAIN["lat_min"]}° to {DOMAIN["lat_max"]}°',
            fontsize=14, fontweight='bold')

# 
sd_output_filename = f"CerraEra_SD_{timestamp}.png"
plt.savefig(sd_output_filename, dpi=100, bbox_inches='tight')
print(f"Standard deviation comparison saved as: {sd_output_filename}")
plt.close(fig2)

# 
ds_ce.close()
ds_er.close()

#
end_time = time.time()
runtime = end_time - start_time
print(f"\nTotal runtime: {runtime:.2f} seconds")
