# -*- coding: utf-8 -*-
"""
Author      : Swapan Mallick (SMHI)
Created on  : 2025-12-15

Description
-----------
This script compares point-based CERRA reanalysis and ERA5-EDA datasets

The input NetCDF files are generated by the preprocessing pipeline of the
Diffusion_CERRA project and contain:
    - Ensemble mean (t2m_mean)
    - Ensemble standard deviation (t2m_std)
at selected spatial points within a predefined European domain.

Main functionalities:
    1. Read point-based NetCDF outputs for CERRA and ERA5-EDA
    2. Extract ensemble mean and standard deviation fields
    3. Generate plots for:
        - Mean temperature comparison
        - Standard deviation comparison
    4. Save PNG figures for each timestamp

Plots are produced in geographic (latitude/longitude) coordinates and are
intended for:
    - Model intercomparison
    - Uncertainty assessment

Input
-----
- cerra_t2m_points_YYYYMMDDHH.nc
- era5eda_t2m_points_YYYYMMDDHH.nc

Output
------
- CerraEra_Mean_YYYYMMDDHH.png
- CerraEra_SD_YYYYMMDDHH.png

Dependencies
------------
xarray, numpy, matplotlib, cartopy

Part of
-------
Diffusion_CERRA: CERRA and ERA5-EDA Ensemble Analysis and Diffusion Modeling Framework
"""

import xarray as xr
import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature
import numpy as np
import os

# Read the NetCDF files
filename1 = "cerra_t2m_points_2020010100.nc"
filename2 = "era5eda_t2m_points_2020010100.nc"

ds_ce = xr.open_dataset(filename1)
ds_er = xr.open_dataset(filename2)

# Extract data from both datasets
data_mean_ce = ds_ce['t2m_mean']
data_sd_ce = ds_ce['t2m_std']
data_mean_er = ds_er['t2m_mean']
data_sd_er = ds_er['t2m_std']

# Get timestamp from filename
def extract_timestamp(filename):
    basename = os.path.basename(filename)
    name_without_ext = os.path.splitext(basename)[0]
    return name_without_ext[-10:]
#
timestamp = extract_timestamp(filename2)

print(f"Timestamp extracted from filename: {timestamp}")

# --- FIGURE 1: MEAN TEMPERATURE COMPARISON ---
fig1, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5))

# Plot settings for mean temperature
vmin_mean, vmax_mean = 200, 300
label_mean = 'Temperature (K)'
cmap_mean = 'jet'

# CERRA Mean plot on the left
lats_ce_mean = data_mean_ce.latitude.values
lons_ce_mean = data_mean_ce.longitude.values
values_ce_mean = data_mean_ce.values

valid_mask_ce_mean = ~np.isnan(values_ce_mean)
if np.any(valid_mask_ce_mean):
    lons_valid_ce_mean = lons_ce_mean[valid_mask_ce_mean]
    lats_valid_ce_mean = lats_ce_mean[valid_mask_ce_mean]
    values_valid_ce_mean = values_ce_mean[valid_mask_ce_mean]
    
    scatter1 = ax1.scatter(lons_valid_ce_mean, lats_valid_ce_mean, c=values_valid_ce_mean,
                          cmap=cmap_mean, s=10, alpha=0.7,
                          vmin=vmin_mean, vmax=vmax_mean)
    ax1.set_xlabel('Longitude')
    ax1.set_ylabel('Latitude')
    ax1.set_title('CERRA t2m Mean')
    ax1.grid(True, alpha=0.3)
    # Add colorbar to CERRA plot
    plt.colorbar(scatter1, ax=ax1, orientation='horizontal', pad=0.05, label=label_mean)

# ERA5EDA Mean plot on the right
lats_er_mean = data_mean_er.latitude.values
lons_er_mean = data_mean_er.longitude.values
values_er_mean = data_mean_er.values

valid_mask_er_mean = ~np.isnan(values_er_mean)
if np.any(valid_mask_er_mean):
    lons_valid_er_mean = lons_er_mean[valid_mask_er_mean]
    lats_valid_er_mean = lats_er_mean[valid_mask_er_mean]
    values_valid_er_mean = values_er_mean[valid_mask_er_mean]
    
    scatter2 = ax2.scatter(lons_valid_er_mean, lats_valid_er_mean, c=values_valid_er_mean,
                          cmap=cmap_mean, s=10, alpha=0.7,
                          vmin=vmin_mean, vmax=vmax_mean)
    ax2.set_xlabel('Longitude')
    ax2.set_ylabel('Latitude')
    ax2.set_title('ERA5-EDA t2m Mean')
    ax2.grid(True, alpha=0.3)
    
    # Add colorbar to ERA5 plot
    plt.colorbar(scatter2, ax=ax2, orientation='horizontal', pad=0.05, label=label_mean)

plt.suptitle(f'Mean Temperature Comparison - {timestamp}', fontsize=14, fontweight='bold')
plt.tight_layout()

# Save the mean comparison plot
mean_output_filename = f"CerraEra_Mean_{timestamp}.png"
plt.savefig(mean_output_filename, dpi=100, bbox_inches='tight')
print(f"Mean comparison saved as: {mean_output_filename}")
#plt.show()

# --- FIGURE 2: STANDARD DEVIATION COMPARISON ---
fig2, (ax3, ax4) = plt.subplots(1, 2, figsize=(12, 5))

# Plot settings for standard deviation
vmin_sd, vmax_sd = 0, 3
label_sd = 'Standard Deviation (K)'
cmap_sd = 'jet'

# CERRA Standard Deviation plot on the left
lats_ce_sd = data_sd_ce.latitude.values
lons_ce_sd = data_sd_ce.longitude.values
values_ce_sd = data_sd_ce.values

valid_mask_ce_sd = ~np.isnan(values_ce_sd)
if np.any(valid_mask_ce_sd):
    lons_valid_ce_sd = lons_ce_sd[valid_mask_ce_sd]
    lats_valid_ce_sd = lats_ce_sd[valid_mask_ce_sd]
    values_valid_ce_sd = values_ce_sd[valid_mask_ce_sd]
    
    scatter3 = ax3.scatter(lons_valid_ce_sd, lats_valid_ce_sd, c=values_valid_ce_sd,
                          cmap=cmap_sd, s=10, alpha=0.7,
                          vmin=vmin_sd, vmax=vmax_sd)
    ax3.set_xlabel('Longitude')
    ax3.set_ylabel('Latitude')
    ax3.set_title('CERRA t2m Standard Deviation')
    ax3.grid(True, alpha=0.3)
    
    # Add colorbar to CERRA SD plot
    plt.colorbar(scatter3, ax=ax3, orientation='horizontal', pad=0.05, label=label_sd)

# ERA5EDA Standard Deviation plot on the right
lats_er_sd = data_sd_er.latitude.values
lons_er_sd = data_sd_er.longitude.values
values_er_sd = data_sd_er.values

valid_mask_er_sd = ~np.isnan(values_er_sd)
if np.any(valid_mask_er_sd):
    lons_valid_er_sd = lons_er_sd[valid_mask_er_sd]
    lats_valid_er_sd = lats_er_sd[valid_mask_er_sd]
    values_valid_er_sd = values_er_sd[valid_mask_er_sd]
    
    scatter4 = ax4.scatter(lons_valid_er_sd, lats_valid_er_sd, c=values_valid_er_sd,
                          cmap=cmap_sd, s=10, alpha=0.7,
                          vmin=vmin_sd, vmax=vmax_sd)
    ax4.set_xlabel('Longitude')
    ax4.set_ylabel('Latitude')
    ax4.set_title('ERA5-EDA t2m Standard Deviation')
    ax4.grid(True, alpha=0.3)
    
    # Add colorbar to ERA5 SD plot
    plt.colorbar(scatter4, ax=ax4, orientation='horizontal', pad=0.05, label=label_sd)

plt.suptitle(f'Standard Deviation Comparison - {timestamp}', fontsize=14, fontweight='bold')
plt.tight_layout()

# Save the standard deviation comparison plot
sd_output_filename = f"CerraEra_SD_{timestamp}.png"
plt.savefig(sd_output_filename, dpi=100, bbox_inches='tight')
print(f"Standard deviation comparison saved as: {sd_output_filename}")
#plt.show()

# Close the datasets
ds_ce.close()
ds_er.close()
