#!/bin/bash
#-------------------------------
#SBATCH --job-name=zarr_convert
#SBATCH --output=zarr_conv.out
#SBATCH --error=zarr_conv.out
#SBATCH --nodes=1
#SBATCH --mem=60GB
#SBATCH --time=36:00:00
#-------------------------------

set -evx

module load conda
conda activate /perm/swe4281/conda/envs/mamba-env

# Paths
input_nc="input_nc"
outputdir="/lus/h2resw01/scratch/swe4281/Fuxing_WORK/ZARR/PLOTS"
zarrpath="/lus/h2resw01/scratch/swe4281/Fuxing_WORK/climate_3km.zarr"

# Variables
variables="ta500 ta700 ta850 ta950 tas"

mkdir -p ${outputdir}
rm -rf ${zarrpath}

# Run script
python3 main_zarr.py \
    --grid_size 106 \
    --era5land_dir ${input_nc} \
    --output_dir ${outputdir} \
    --zarr_path ${zarrpath} \
    --variables ${variables}
