#!/bin/bash -l
#-------------------------------------------------
#SBATCH -A naiss2025-1-5
#SBATCH -p shared
#SBATCH --job-name=zarr_verification
#SBATCH --output=zarr_verification.out
#SBATCH --error=zarr_verification.out
#SBATCH -n 1
#SBATCH --mem=60G
#SBATCH --time=36:00:00
#-------------------------------------------------

#set -euo pipefail
set -x

# =================================================
# USER-DEFINED VARIABLES (DEFINE FIRST)
# =================================================

# Input / Output
#outputdir="${PWD}/PLOTS"
zarrinput="/cfs/klemming/scratch/y/yarongc/VERIFICATION_MARCH2026/CERRA5.5km_JAN2024.zarr"
#zarrinput="/ec/res4/scratch/swe4281/CERRA_DATA2026/all_zarr-out_2024.zar"
outputdir="/cfs/klemming/scratch/y/yarongc/VERIFICATION_MARCH2026/PLOTS_VERIFICATION"
# =================================================
# PREPARE OUTPUT DIRECTORY
# =================================================
rm -rf "${outputdir}"
mkdir -p "${outputdir}"

# Geographic domain
latmin=54.0
#latmin=49.8
latmax=71.0
lonmin=4.0
#lonmin=-1.1
lonmax=25.0
#lonmax=30.0

# Variables to plot (DEFINE AS LIST FIRST)
# ----Variables for CERRA 5.5 Km 
variables=(
    t2m
)
#----Variables for CERRA-MEAN and ERA5-EDA
#variables=(
#    t2m_cerra_mean
#    t2m_era5_mean
#    t2m_cerra_std
#    t2m_era5_std
#)

# =================================================
# LOAD ENVIRONMENT
# =================================================
ml PDC
ml miniconda3/25.3.1-1-cpeGNU-24.11
source activate torch_rocm

# =================================================
# RUN PYTHON SCRIPT
# =================================================
#python verification_statistics.py \
#python verification_statistics_all.py \
python verification_statistics_CERRA5P5.py \
    --zarr-path "${zarrinput}" \
    --output-dir "${outputdir}" \
    --lat-min "${latmin}" \
    --lat-max "${latmax}" \
    --lon-min "${lonmin}" \
    --lon-max "${lonmax}"  \
    --csv-file /cfs/klemming/scratch/y/yarongc/VERIFICATION_MARCH2026/t2m_jan2024.csv

echo "Job completed successfully."
