#!/bin/bash
#-------------------------------------------------
#SBATCH --job-name=zarr_plots
#SBATCH --output=zarr_plots.out
#SBATCH --error=zarr_plots.out
#SBATCH --nodes=1
#SBATCH --mem=60G
#SBATCH --time=36:00:00
#-------------------------------------------------

#set -euo pipefail
set -x

# =================================================
# USER-DEFINED VARIABLES (DEFINE FIRST)
# =================================================

# Input / Output
#zarrinput="${PWD}/zarr-out"
#outputdir="${PWD}/PLOTS"
zarrinput="/ec/res4/scratch/swe4281/CERRA_DATA2026/FINAL_zarr-out_2015-2024"
outputdir="/ec/res4/scratch/swe4281/CERRA_DATA2026/ZARR_PLOTS"
# =================================================
# PREPARE OUTPUT DIRECTORY
# =================================================
rm -rf "${outputdir}"
mkdir -p "${outputdir}"

# Geographic domain
latmin=54.0
#latmin=49.8
latmax=71.0
lonmin=4.0
#lonmin=-1.1
lonmax=30.0

# Variables to plot (DEFINE AS LIST FIRST)
variables=(
    t2m_cerra_mean
    t2m_era5_mean
    t2m_cerra_std
    t2m_era5_std
)

# =================================================
# LOAD ENVIRONMENT
# =================================================
module load conda
conda activate mamba-env

# =================================================
# RUN PYTHON SCRIPT
# =================================================
python extract_zarr_to_png.py \
    --zarr-path "${zarrinput}" \
    --output-dir "${outputdir}" \
    --variables "${variables[@]}" \
    --lat-min "${latmin}" \
    --lat-max "${latmax}" \
    --lon-min "${lonmin}" \
    --lon-max "${lonmax}"\
    --full-bleed 

echo "Job completed successfully."
