#!/bin/sh
#-------------------------------
#SBATCH --job-name=ZARRDDPM_Training
#SBATCH --output=ZARRt2m_log.out
#SBATCH --error=ZARRt2m_log.out
#SBATCH --qos=ng
#SBATCH --nodes=1
#SBATCH --mem=60GB
#SBATCH --gpus=1
#SBATCH --time=36:00:00
#-------------------------------

set -evx
module load conda
conda activate ddenv_v2

# CUDA-aware MPI & fragmentation mitigation
export OMPI_MCA_opal_cuda_support=true
export OMPI_MCA_pml=ucx
export UCX_MEMTYPE_CACHE=n
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export MASTER_PORT=$((10000 + RANDOM % 50000))

TYPE="DDPM"
INPUT="/lus/h2resw01/scratch/swe4281/CERRA_DATA2026/ML_DATA_ALL/2015-2023-no2019.zarr"
OUTPUT="/ec/res4/scratch/swe4281/CERRA_DATA2026/DDMP_MODEL/${TYPE}_mlcheck_zarr"
rm -rf ${OUTPUT}
mkdir -p ${OUTPUT}
echo  ${OUTPUT}

# Lowered batch + microbatch + enable fp16
MODEL_FLAGS="--in_channels 2 --save_interval 2000 --image_size 256 --num_channels 64"   # reduce model size if needed
TOTALSTEP="--steps 30000"
TRAIN_FLAGS="--lr 1e-4 --batch_size 8 --microbatch 4 --use_fp16 True"

mkdir -p $OUTPUT

# Launch
python3  Train_Main_zarr.py \
    --data_dir $INPUT --TRAIN_OUT $OUTPUT \
      $MODEL_FLAGS $TOTALSTEP $TRAIN_FLAGS
