#!/bin/bash -l
#-------------------------------
#SBATCH -A naiss2025-1-5-gpu
#SBATCH -J ZARRDDPM_Training
#SBATCH -p gpu
#SBATCH --output=ZARRt2m_log.out
#SBATCH --error=ZARRt2m_log.out
#SBATCH -N 1
#SBATCH --mem=60GB
#SBATCH --gpus=1
#SBATCH --time=24:00:00
#-------------------------------

set -evx
ml PDC
ml miniconda3/25.3.1-1-cpeGNU-24.11
source activate torch_rocm

# Change the correct path in all the places.

PROJECT_ROOT="PATH/Diffusion_CERRA/diffusion_April15"
# project root for imports
export PYTHONPATH=${PROJECT_ROOT}:${PYTHONPATH:-}

# CUDA-aware MPI & fragmentation mitigation
export OMPI_MCA_opal_cuda_support=true
export OMPI_MCA_pml=ucx
export UCX_MEMTYPE_CACHE=n
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
export MASTER_PORT=$((10000 + RANDOM % 50000))

TYPE="DDPM"
EVA="CRPS"

INPUT_VARS=(
  t2m_era5_mean
  t2m_era5_std
  #d2m_era5_mean
  #sp_era5_mean
  #u10_era5_mean
  #v10_era5_mean
)

TARGET_VARS=(
  t2m_cerra_mean
  t2m_cerra_std
)

USE_SEASONAL=1 # 0 means no seasonal used
SEASONAL_CHANNELS=12

SEASONAL_FLAGS=""
if [ "${USE_SEASONAL}" = "1" ]; then
  SEASONAL_FLAGS="--add_seasonal_cond --seasonal_channels ${SEASONAL_CHANNELS}"
fi

cd ${PROJECT_ROOT}

cd src_diffusion
rm -f diffusion_gaussian.py

if [ "${EVA}" = "MSE" ]; then
    ln -s diffusion_gaussian_MSE.py diffusion_gaussian.py
elif [ "${EVA}" = "CRPS" ]; then
    ln -s diffusion_gaussian_CRPS.py diffusion_gaussian.py
else
    echo "Unknown EVA type: ${EVA}"
    exit 1
fi

rm -rf __pycache__
cd ..

INPUT="PATH/all_zarr-out_2015-2023.zar"
OUTPUT="PATH/${TYPE}_mlcheck_zarr/${EVA}"
rm -rf ${OUTPUT}
mkdir -p ${OUTPUT}
echo  ${OUTPUT}

# Lowered batch + microbatch + enable fp16
MODEL_FLAGS="--save_interval 2000 --image_size 1024 --num_channels 64"   # reduce model size if needed
TOTALSTEP="--steps 25000"
DIFFUSION_STEPS=4000
TIMESTEP_RESPACING=""
TRAIN_FLAGS="--lr 1e-4 --batch_size 8 --microbatch 4 --use_fp16 True"

mkdir -p $OUTPUT

# Launch
python3  train_ml/Train_main.py \
  --data_dir $INPUT \
  --TRAIN_OUT $OUTPUT \
  --input_vars "${INPUT_VARS[@]}" \
  --target_vars "${TARGET_VARS[@]}" \
  ${SEASONAL_FLAGS} \
  --diffusion_steps ${DIFFUSION_STEPS} \
  --timestep_respacing "${TIMESTEP_RESPACING}" \
  $MODEL_FLAGS $TOTALSTEP $TRAIN_FLAGS
