#!/bin/sh
#-------------------------------
#SBATCH --job-name=1DDPM_Training
#SBATCH --output=1t2m_log.out
#SBATCH --error=1t2m_log.out
#SBATCH --qos=ng
#SBATCH --nodes=1
#SBATCH --mem=60GB
#SBATCH --gpus=1
#SBATCH --time=36:00:00
#-------------------------------

set -evx
module load conda
conda activate ddenv_v2

# CUDA-aware MPI & fragmentation mitigation
export OMPI_MCA_opal_cuda_support=true
export OMPI_MCA_pml=ucx
export UCX_MEMTYPE_CACHE=n
export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True

TYPE="DDPM_2015to2023"
INPUT="/ec/res4/scratch/swe4281/CERRA_DATA2026/PLOTS_ALL_YY2015_2024/TRAIN_IN"
OUTPUT="/ec/res4/scratch/swe4281/CERRA_DATA2026/PLOTS_ALL_YY2015_2024/ML_DDPM/${TYPE}"

# Lowered batch + microbatch + enable fp16
MODEL_FLAGS="--save_interval 2000 --image_size 256 --num_channels 64"   # reduce model size if needed
TOTALSTEP="--steps 20000"
TRAIN_FLAGS="--lr 1e-4 --batch_size 8 --microbatch 4 --use_fp16 True"

mkdir -p $OUTPUT

# Launch
srun --mpi=pmi2 torchrun --nproc_per_node=1 Train_Main_imag.py \
    --data_dir $INPUT --TRAIN_OUT $OUTPUT \
      $MODEL_FLAGS $TOTALSTEP $TRAIN_FLAGS
