#!/bin/bash
#-------------------------------------------------
##SBATCH --job-name=zarr_plots
##SBATCH --output=zarr_plots.out
##SBATCH --error=zarr_plots.out
##SBATCH --nodes=1
##SBATCH --mem=60G
##SBATCH --time=36:00:00
#-------------------------------------------------

#set -euo pipefail
set -x

# =================================================
# USER-DEFINED VARIABLES (DEFINE FIRST)
# =================================================

# Input / Output
#zarrinput="${PWD}/zarr-out"
#outputdir="${PWD}/PLOTS"
zarrinput="/cfs/klemming/scratch/s/swapanm/VERIFICATION_MARCH2026/CERRA5.5km_JAN2024.zarr"
outputdir="/cfs/klemming/scratch/s/swapanm/VERIFICATION_MARCH2026/CERRA_ML_DIFF_JAN2024"
# =================================================
# PREPARE OUTPUT DIRECTORY
# =================================================
#rm -rf "${outputdir}"
mkdir -p "${outputdir}"

# Geographic domain
latmin=54.0
#latmin=49.8
latmax=71.0
lonmin=4.0
#lonmin=-1.1
lonmax=25.0
#lonmax=30.0

# Variables to plot (DEFINE AS LIST FIRST)
#variables=(
#    t2m_cerra_men
#    t2m_era5_mean
#)
variables=(
    t2m
)

# =================================================
# LOAD ENVIRONMENT
# =================================================
ml PDC
ml miniconda3/25.3.1-1-cpeGNU-24.11
source activate torch_rocm

# =================================================
# RUN PYTHON SCRIPT
# =================================================
python cerra_ML_DIFF.py \
    --zarr-path "${zarrinput}" \
    --output-dir "${outputdir}" \
    --variable "${variables[@]}" \
    --lat-min "${latmin}" \
    --lat-max "${latmax}" \
    --lon-min "${lonmin}" \
    --lon-max "${lonmax}" # \
    #--csv-file /cfs/klemming/home/s/swapanm/Diffusion_CERRA/diffusion_May26/VERIFICATION_MARCH2026/t2m_jan2024.csv
echo "Job completed successfully."
